### ISSUE TITLE
`Uncaught Error: Call to undefined function _HumbugBox44cdd6d36ff3\array_any() ` for 6.8.1 release

### ISSUE THREAD

**Issue by chenrui333** [vimeo/psalm#11322]
👋 while testing psalm.phar 6.8.1 release, seeing some crash issue as below:

```
==> /home/linuxbrew/.linuxbrew/Cellar/psalm/6.8.1/bin/psalm --init
  Uncaught Error: Call to undefined function _HumbugBox44cdd6d36ff3\array_any() in phar:///home/linuxbrew/.linuxbrew/Cellar/psalm/6.8.1/libexec/psalm/src/Psalm/Internal/Fork/PsalmRestarter.php:52
  Stack trace:
  #0 phar:///home/linuxbrew/.linuxbrew/Cellar/psalm/6.8.1/libexec/psalm/vendor/composer/xdebug-handler/src/XdebugHandler.php(116): Psalm\Internal\Fork\PsalmRestarter->requiresRestart(false)
  #1 phar:///home/linuxbrew/.linuxbrew/Cellar/psalm/6.8.1/libexec/psalm/src/Psalm/Internal/Cli/Psalm.php(645): _HumbugBox44cdd6d36ff3\Composer\XdebugHandler\XdebugHandler->check()
  #2 phar:///home/linuxbrew/.linuxbrew/Cellar/psalm/6.8.1/libexec/psalm/src/Psalm/Internal/Cli/Psalm.php(234): Psalm\Internal\Cli\Psalm::restart(Array, 1, 1, Object(Psalm\Progress\LongProgress))
  #3 phar:///home/linuxbrew/.linuxbrew/Cellar/psalm/6.8.1/libexec/psalm/psalm(7): Psalm\Internal\Cli\Psalm::run(Array)
  #4 /home/linuxbrew/.linuxbrew/Cellar/psalm/6.8.1/libexec/psalm(14): require('phar:///home/li...')
  #5 /home/linuxbrew/.linuxbrew/Cellar/psalm/6.8.1/bin/psalm(2): require('/home/linuxbrew...')
  #6 {main}
  (Psalm 6.8.1@f12f96cde537a424fe2a9366105b5e[71](https://github.com/Homebrew/homebrew-core/actions/runs/13414729294/job/37472910776?pr=208273#step:4:72)46d4fc23 crashed due to an uncaught Throwable)
  Calculating best config level based on project files
  Error: psalm: failed
  An exception occurred within a child process:
    Minitest::Assertion: Expected: 0
    Actual: 1
```

relates to https://github.com/Homebrew/homebrew-core/pull/208273

**Comment by majoskorec** [comment]
I have the same problem on several of my projects. it started with version 6.8.0

**Comment by pereorga** [comment]
I can still reproduce it with 6.8.2:

```
vendor/bin/psalm.phar --threads=1 --no-cache --no-progress
Uncaught Error: Call to undefined function _HumbugBoxd84cf39e5d32\array_any() in phar:///Users/pere/dev/pccd/vendor/psalm/phar/psalm.phar/src/Psalm/Internal/Fork/PsalmRestarter.php:52
Stack trace:
#0 phar:///Users/pere/dev/pccd/vendor/psalm/phar/psalm.phar/vendor/composer/xdebug-handler/src/XdebugHandler.php(117): Psalm\Internal\Fork\PsalmRestarter->requiresRestart(false)
#1 phar:///Users/pere/dev/pccd/vendor/psalm/phar/psalm.phar/src/Psalm/Internal/Cli/Psalm.php(645): _HumbugBoxd84cf39e5d32\Composer\XdebugHandler\XdebugHandler->check()
#2 phar:///Users/pere/dev/pccd/vendor/psalm/phar/psalm.phar/src/Psalm/Internal/Cli/Psalm.php(234): Psalm\Internal\Cli\Psalm::restart(Array, 1, 10, Object(Psalm\Progress\VoidProgress))
#3 phar:///Users/pere/dev/pccd/vendor/psalm/phar/psalm.phar/psalm(7): Psalm\Internal\Cli\Psalm::run(Array)
#4 /Users/pere/dev/pccd/vendor/psalm/phar/psalm.phar(14): require('phar:///Users/p...')
#5 /Users/pere/dev/pccd/vendor/bin/psalm.phar(119): include('/Users/pere/dev...')
#6 {main}
(Psalm 6.8.2@720ed6b578ac24f9543c65c3d4cecea0ff348ccd crashed due to an uncaught Throwable)
Script vendor/bin/psalm.phar --threads=1 --no-cache --no-progress handling the psalm event returned with error code 1

MACQG9CTF7QW2:pccd pere$ vendor/bin/psalm.phar --version
Psalm 6.8.2@720ed6b578ac24f9543c65c3d4cecea0ff348ccd
```

**Comment by danog** [comment]
Fixed, now builds are also reproducible.

**Comment by bastienrossi** [comment]
Hi, the problem still seems to be present.
In my case i use the following command : 
```bash
psalm --no-diff --no-cache --monochrome --long-progress
      --report=.psalm-reports/report.console
      --report=.psalm-reports/report.sarif
      --report=.psalm-reports/report.junit.xml
```

**Comment by danog** [comment]
What version of php and psalm are you using?

**Comment by bastienrossi** [comment]
vimeo/psalm (6.8.6) and psalm/plugin-phpunit (0.19.2).
This bug occurs in my CI running tests on php 8.2 and php 8.3.
Same error on both versions.

**Comment by danog** [comment]
Fixed in the next release
