### ISSUE TITLE
Uncaught Amp\Parallel\Context\ContextException: Worker exited due to signal 9!

### ISSUE THREAD

**Issue by s1lver** [vimeo/psalm#11394]
After upgrading from version **5.26.1** to version **6.10.0**, PSALM started crashing with the error:

> vendor/bin/psalm --no-cache --threads=1
> 
> Running on PHP 8.3.20, Psalm 6.10.0@9c0add4eb88d4b169ac04acb7c679918cbb9c252.
> 
> JIT acceleration: ON
> 
> JIT compilation in progress... Done.
> 
> Target PHP version: 8.3 (set by config file) (unsupported extensions: opentelemetry, fileinfo).
> 
> 
> Scanning files...
> 
> 20673 / 20673...Uncaught Amp\Parallel\Context\ContextException: Worker exited due to signal 9! in /var/www/vendor/vimeo/psalm/src/Psalm/Internal/Fork/ForkContext.php:239
> Stack trace:
> #0 /var/www/vendor/vimeo/psalm/src/Psalm/Internal/Fork/ForkContext.php(250): Psalm\Internal\Fork\ForkContext->checkExit()
> #1 /var/www/vendor/amphp/parallel/src/Worker/Internal/ContextWorker.php(75): Psalm\Internal\Fork\ForkContext->close()
> #2 /var/www/vendor/amphp/parallel/src/Worker/Internal/ContextWorker.php(120): Amp\Parallel\Worker\Internal\ContextWorker::Amp\Parallel\Worker\Internal\{closure}(Object(Amp\Parallel\Context\ContextException), NULL)
> #3 /var/www/vendor/revolt/event-loop/src/EventLoop/Internal/AbstractDriver.php(430): Amp\Parallel\Worker\Internal\ContextWorker::Amp\Parallel\Worker\Internal\{closure}()
> #4 /var/www/vendor/revolt/event-loop/src/EventLoop/Internal/AbstractDriver.php(567): Revolt\EventLoop\Internal\AbstractDriver->invokeMicrotasks()
> #5 [internal function]: Revolt\EventLoop\Internal\AbstractDriver->Revolt\EventLoop\Internal\{closure}()
> #6 /var/www/vendor/revolt/event-loop/src/EventLoop/Internal/DriverSuspension.php(64): Fiber->resume(NULL)
> #7 /var/www/vendor/revolt/event-loop/src/EventLoop/Internal/AbstractDriver.php(430): Revolt\EventLoop\Internal\DriverSuspension::Revolt\EventLoop\Internal\{closure}()
> #8 /var/www/vendor/revolt/event-loop/src/EventLoop/Internal/AbstractDriver.php(621): Revolt\EventLoop\Internal\AbstractDriver->invokeMicrotasks()
> #9 [internal function]: Revolt\EventLoop\Internal\AbstractDriver->Revolt\EventLoop\Internal\{closure}()
> #10 /var/www/vendor/revolt/event-loop/src/EventLoop/Internal/AbstractDriver.php(502): Fiber->resume()
> #11 /var/www/vendor/revolt/event-loop/src/EventLoop/Internal/AbstractDriver.php(558): Revolt\EventLoop\Internal\AbstractDriver->invokeCallbacks()
> #12 [internal function]: Revolt\EventLoop\Internal\AbstractDriver->Revolt\EventLoop\Internal\{closure}()
> #13 /var/www/vendor/revolt/event-loop/src/EventLoop/Internal/AbstractDriver.php(96): Fiber->resume()
> #14 /var/www/vendor/revolt/event-loop/src/EventLoop/Internal/DriverSuspension.php(117): Revolt\EventLoop\Internal\AbstractDriver->Revolt\EventLoop\Internal\{closure}()
> #15 /var/www/vendor/amphp/amp/src/Future.php(251): Revolt\EventLoop\Internal\DriverSuspension->suspend()
> #16 /var/www/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Scanner.php(326): Amp\Future->await()
> #17 /var/www/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Scanner.php(267): Psalm\Internal\Codebase\Scanner->scanFilePaths(4)
> #18 /var/www/vendor/vimeo/psalm/src/Psalm/Codebase.php(442): Psalm\Internal\Codebase\Scanner->scanFiles(Object(Psalm\Internal\Codebase\ClassLikes), 4)
> #19 /var/www/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(481): Psalm\Codebase->scanFiles(4)
> #20 /var/www/vendor/vimeo/psalm/src/Psalm/Internal/Cli/Psalm.php(394): Psalm\Internal\Analyzer\ProjectAnalyzer->check('/var/www', true)
> #21 /var/www/vendor/vimeo/psalm/psalm(9): Psalm\Internal\Cli\Psalm::run(Array)
> #22 /var/www/vendor/bin/psalm(119): include('/var/www/vendor...')
> #23 {main}
> 
> Next Revolt\EventLoop\UncaughtThrowable: Uncaught Amp\Parallel\Context\ContextException thrown in event loop callback Amp\Parallel\Worker\Internal\ContextWorker::Amp\Parallel\Worker\Internal\{closure} defined in /var/www/vendor/amphp/parallel/src/Worker/Internal/ContextWorker.php:116; use Revolt\EventLoop::setErrorHandler() to gracefully handle such exceptions: Worker exited due to signal 9! in /var/www/vendor/revolt/event-loop/src/EventLoop/UncaughtThrowable.php:13
> Stack trace:
> #0 /var/www/vendor/revolt/event-loop/src/EventLoop/Internal/AbstractDriver.php(405): Revolt\EventLoop\UncaughtThrowable::throwingCallback(Object(Closure), Object(Amp\Parallel\Context\ContextException))
> #1 /var/www/vendor/revolt/event-loop/src/EventLoop/Internal/DriverSuspension.php(127): Revolt\EventLoop\Internal\AbstractDriver::Revolt\EventLoop\Internal\{closure}()
> #2 /var/www/vendor/amphp/amp/src/Future.php(251): Revolt\EventLoop\Internal\DriverSuspension->suspend()
> #3 /var/www/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Scanner.php(326): Amp\Future->await()
> #4 /var/www/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Scanner.php(267): Psalm\Internal\Codebase\Scanner->scanFilePaths(4)
> #5 /var/www/vendor/vimeo/psalm/src/Psalm/Codebase.php(442): Psalm\Internal\Codebase\Scanner->scanFiles(Object(Psalm\Internal\Codebase\ClassLikes), 4)
> #6 /var/www/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(481): Psalm\Codebase->scanFiles(4)
> #7 /var/www/vendor/vimeo/psalm/src/Psalm/Internal/Cli/Psalm.php(394): Psalm\Internal\Analyzer\ProjectAnalyzer->check('/var/www', true)
> #8 /var/www/vendor/vimeo/psalm/psalm(9): Psalm\Internal\Cli\Psalm::run(Array)
> #9 /var/www/vendor/bin/psalm(119): include('/var/www/vendor...')
> #10 {main}
> (Psalm 6.10.0@9c0add4eb88d4b169ac04acb7c679918cbb9c252 crashed due to an uncaught Throwable)
> Fatal error: Uncaught Amp\Parallel\Context\ContextException: Worker exited due to signal 9! in /var/www/vendor/vimeo/psalm/src/Psalm/Internal/Fork/ForkContext.php:239
> Stack trace:
> #0 /var/www/vendor/vimeo/psalm/src/Psalm/Internal/Fork/ForkContext.php(250): Psalm\Internal\Fork\ForkContext->checkExit()
> #1 /var/www/vendor/vimeo/psalm/src/Psalm/Internal/Fork/ForkContext.php(196): Psalm\Internal\Fork\ForkContext->close()
> #2 [internal function]: Psalm\Internal\Fork\ForkContext->__destruct()
> #3 {main}
>   thrown in /var/www/vendor/vimeo/psalm/src/Psalm/Internal/Fork/ForkContext.php on line 239

If you roll back the version, the check starts as before.

**Comment by danog** [comment]
This is caused by the OS killing the Psalm worker due to an OOM, try running with --debug and --debug-by-line to see what file is causing the high RAM usage

**Comment by s1lver** [comment]
> This is caused by the OS killing the Psalm worker due to an OOM, try running with --debug and --debug-by-line to see what file is causing the high RAM usage

I checked all versions starting from **6.0.0** and found out that the problem starts with version **6.1.0**

No errors on all versions:
`vendor/bin/psalm --no-cache --threads=1 --debug --debug-by-line`

Errors on all versions:
`vendor/bin/psalm --no-cache --threads=1`

**Comment by danog** [comment]
I still need a proper reproducer to help

**Comment by danog** [comment]
Please try using the official docker image, instead

**Comment by danog** [comment]
6.13.0 with the arrayCache="false" config should help with this.

**Comment by s1lver** [comment]
@danog Its not work for me

> /var/www # vendor/bin/psalm --no-cache --threads=1
> 
> Running on PHP 8.4.12, Psalm 6.13.1@1e3b7f0a8ab32b23197b91107adc0a7ed8a05b51.
> 
> JIT acceleration: ON
> 
> JIT compilation in progress... Done.
> 
> Target PHP version: 8.4 (set by config file) (unsupported extensions: opentelemetry, fileinfo).
> 
> 
> Scanning files...
> 
> 20842 / 20842...Uncaught Amp\Parallel\Context\ContextException: Worker exited due to signal 9: the process was likely killed by the OOM killer, try increasing the swap space or use the arrayCache="false" config to reduce memory usage! in /var/www/vendor/vimeo/psalm/src/Psalm/Internal/Fork/ForkContext.php:242
> Stack trace:
> #0 /var/www/vendor/vimeo/psalm/src/Psalm/Internal/Fork/ForkContext.php(253): Psalm\Internal\Fork\ForkContext->checkExit()
> #1 /var/www/vendor/amphp/parallel/src/Worker/Internal/ContextWorker.php(75): Psalm\Internal\Fork\ForkContext->close()
> #2 /var/www/vendor/amphp/parallel/src/Worker/Internal/ContextWorker.php(120): Amp\Parallel\Worker\Internal\ContextWorker::{closure:Amp\Parallel\Worker\Internal\ContextWorker::__construct():58}(Object(Amp\Parallel\Context\ContextException), NULL)
> #3 /var/www/vendor/revolt/event-loop/src/EventLoop/Internal/AbstractDriver.php(430): Amp\Parallel\Worker\Internal\ContextWorker::{closure:Amp\Parallel\Worker\Internal\ContextWorker::receive():116}()
> #4 /var/www/vendor/revolt/event-loop/src/EventLoop/Internal/AbstractDriver.php(621): Revolt\EventLoop\Internal\AbstractDriver->invokeMicrotasks()
> #5 [internal function]: Revolt\EventLoop\Internal\AbstractDriver->{closure:Revolt\EventLoop\Internal\AbstractDriver::createCallbackFiber():565}()
> #6 /var/www/vendor/revolt/event-loop/src/EventLoop/Internal/DriverSuspension.php(64): Fiber->resume(NULL)
> #7 /var/www/vendor/revolt/event-loop/src/EventLoop/Internal/AbstractDriver.php(430): Revolt\EventLoop\Internal\DriverSuspension::{closure:Revolt\EventLoop\Internal\DriverSuspension::resume():61}()
> #8 /var/www/vendor/revolt/event-loop/src/EventLoop/Internal/AbstractDriver.php(621): Revolt\EventLoop\Internal\AbstractDriver->invokeMicrotasks()
> #9 [internal function]: Revolt\EventLoop\Internal\AbstractDriver->{closure:Revolt\EventLoop\Internal\AbstractDriver::createCallbackFiber():565}()
> #10 /var/www/vendor/revolt/event-loop/src/EventLoop/Internal/AbstractDriver.php(502): Fiber->resume()
> #11 /var/www/vendor/revolt/event-loop/src/EventLoop/Internal/AbstractDriver.php(558): Revolt\EventLoop\Internal\AbstractDriver->invokeCallbacks()
> #12 [internal function]: Revolt\EventLoop\Internal\AbstractDriver->{closure:Revolt\EventLoop\Internal\AbstractDriver::createLoopFiber():538}()
> #13 /var/www/vendor/revolt/event-loop/src/EventLoop/Internal/AbstractDriver.php(96): Fiber->resume()
> #14 /var/www/vendor/revolt/event-loop/src/EventLoop/Internal/DriverSuspension.php(117): Revolt\EventLoop\Internal\AbstractDriver->{closure:Revolt\EventLoop\Internal\AbstractDriver::__construct():90}()
> #15 /var/www/vendor/amphp/amp/src/Future.php(251): Revolt\EventLoop\Internal\DriverSuspension->suspend()
> #16 /var/www/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Scanner.php(325): Amp\Future->await()
> #17 /var/www/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Scanner.php(266): Psalm\Internal\Codebase\Scanner->scanFilePaths(4)
> #18 /var/www/vendor/vimeo/psalm/src/Psalm/Codebase.php(444): Psalm\Internal\Codebase\Scanner->scanFiles(Object(Psalm\Internal\Codebase\ClassLikes), 4)
> #19 /var/www/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(429): Psalm\Codebase->scanFiles(4)
> #20 /var/www/vendor/vimeo/psalm/src/Psalm/Internal/Cli/Psalm.php(400): Psalm\Internal\Analyzer\ProjectAnalyzer->check('/var/www', false)
> #21 /var/www/vendor/vimeo/psalm/psalm(9): Psalm\Internal\Cli\Psalm::run(Array)
> #22 /var/www/vendor/bin/psalm(119): include('/var/www/vendor...')
> #23 {main}
> 
> Next Revolt\EventLoop\UncaughtThrowable: Uncaught Amp\Parallel\Context\ContextException thrown in event loop callback Amp\Parallel\Worker\Internal\ContextWorker::{closure:Amp\Parallel\Worker\Internal\ContextWorker::receive():116} defined in /var/www/vendor/amphp/parallel/src/Worker/Internal/ContextWorker.php:116; use Revolt\EventLoop::setErrorHandler() to gracefully handle such exceptions: Worker exited due to signal 9: the process was likely killed by the OOM killer, try increasing the swap space or use the arrayCache="false" config to reduce memory usage! in /var/www/vendor/revolt/event-loop/src/EventLoop/UncaughtThrowable.php:13
> Stack trace:
> #0 /var/www/vendor/revolt/event-loop/src/EventLoop/Internal/AbstractDriver.php(405): Revolt\EventLoop\UncaughtThrowable::throwingCallback(Object(Closure), Object(Amp\Parallel\Context\ContextException))
> #1 /var/www/vendor/revolt/event-loop/src/EventLoop/Internal/DriverSuspension.php(127): Revolt\EventLoop\Internal\AbstractDriver::{closure:Revolt\EventLoop\Internal\AbstractDriver::error():403}()
> #2 /var/www/vendor/amphp/amp/src/Future.php(251): Revolt\EventLoop\Internal\DriverSuspension->suspend()
> #3 /var/www/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Scanner.php(325): Amp\Future->await()
> #4 /var/www/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Scanner.php(266): Psalm\Internal\Codebase\Scanner->scanFilePaths(4)
> #5 /var/www/vendor/vimeo/psalm/src/Psalm/Codebase.php(444): Psalm\Internal\Codebase\Scanner->scanFiles(Object(Psalm\Internal\Codebase\ClassLikes), 4)
> #6 /var/www/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(429): Psalm\Codebase->scanFiles(4)
> #7 /var/www/vendor/vimeo/psalm/src/Psalm/Internal/Cli/Psalm.php(400): Psalm\Internal\Analyzer\ProjectAnalyzer->check('/var/www', false)
> #8 /var/www/vendor/vimeo/psalm/psalm(9): Psalm\Internal\Cli\Psalm::run(Array)
> #9 /var/www/vendor/bin/psalm(119): include('/var/www/vendor...')
> #10 {main}
> (Psalm 6.13.1@1e3b7f0a8ab32b23197b91107adc0a7ed8a05b51 crashed due to an uncaught Throwable)
> Fatal error: Uncaught Amp\Parallel\Context\ContextException: Worker exited due to signal 9: the process was likely killed by the OOM killer, try increasing the swap space or use the arrayCache="false" config to reduce memory usage! in /var/www/vendor/vimeo/psalm/src/Psalm/Internal/Fork/ForkContext.php:242
> Stack trace:
> #0 /var/www/vendor/vimeo/psalm/src/Psalm/Internal/Fork/ForkContext.php(253): Psalm\Internal\Fork\ForkContext->checkExit()
> #1 /var/www/vendor/vimeo/psalm/src/Psalm/Internal/Fork/ForkContext.php(196): Psalm\Internal\Fork\ForkContext->close()
> #2 [internal function]: Psalm\Internal\Fork\ForkContext->__destruct()
> #3 {main}
>   thrown in /var/www/vendor/vimeo/psalm/src/Psalm/Internal/Fork/ForkContext.php on line 242


My config:
```xml
<psalm
    errorLevel="1"
    findUnusedBaselineEntry="true"
    findUnusedCode="false"
    allowStringToStandInForClass="true"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns="https://getpsalm.org/schema/config"
    xsi:schemaLocation="https://getpsalm.org/schema/config vendor/vimeo/psalm/config.xsd"
    cacheDirectory="runtime/.psalm-cache"
    phpVersion="8.4"
    resolveFromConfigFile="true"
    strictBinaryOperands="false"
    arrayCache="false"
>
```

**Comment by s1lver** [comment]
If the number of files that need to be processed is less than 10,000, this problem does not occur. That is, it works for small projects or packages. However, when a large project needs to be processed, a crash occurs.

If you increase the swap beyond 1GB, the error will be different:

> Running on PHP 8.4.12, Psalm 6.13.1@1e3b7f0a8ab32b23197b91107adc0a7ed8a05b51.
> 
> JIT acceleration: ON
> 
> JIT compilation in progress... Done.
> 
> Target PHP version: 8.4 (set by config file) (unsupported extensions: opentelemetry, fileinfo).
> 
> 
> Scanning files...
> 
> 20842 / 20842.../var/www # Uncaught Amp\ByteStream\ClosedException: The stream was closed in /var/www/vendor/amphp/byte-stream/src/WritableResourceStream.php:98
> Stack trace:
> #0 /var/www/vendor/amphp/byte-stream/src/WritableResourceStream.php(248): Amp\ByteStream\WritableResourceStream::{closure:{closure:Amp\ByteStream\WritableResourceStream::__construct():77}:98}()
> #1 /var/www/vendor/amphp/socket/src/ResourceSocket.php(129): Amp\ByteStream\WritableResourceStream->write('\x00Psalm\\CodeLoca...')
> #2 /var/www/vendor/amphp/byte-stream/src/StreamChannel.php(69): Amp\Socket\ResourceSocket->write('\x00\x00\x18\xAD\x17O:44:"Amp\\...')
> #3 /var/www/vendor/amphp/parallel/src/Context/Internal/ContextChannel.php(29): Amp\ByteStream\StreamChannel->send('\x00\x00\x18\xAD\x17O:44:"Amp\\...')
> #4 /var/www/vendor/amphp/parallel/src/Worker/Internal/task-runner.php(77): Amp\Parallel\Context\Internal\ContextChannel->send(Object(Amp\Parallel\Worker\Internal\TaskSuccess))
> #5 /var/www/vendor/revolt/event-loop/src/EventLoop/Internal/AbstractDriver.php(430): Psalm\Internal\Fork\ForkContext::{closure:{closure:/var/www/vendor/amphp/parallel/src/Worker/Internal/task-runner.php:14}:47}()
> #6 /var/www/vendor/revolt/event-loop/src/EventLoop/Internal/AbstractDriver.php(621): Revolt\EventLoop\Internal\AbstractDriver->invokeMicrotasks()
> #7 [internal function]: Revolt\EventLoop\Internal\AbstractDriver->{closure:Revolt\EventLoop\Internal\AbstractDriver::createCallbackFiber():565}()
> #8 /var/www/vendor/revolt/event-loop/src/EventLoop/Internal/DriverSuspension.php(64): Fiber->resume(Object(Closure))
> #9 /var/www/vendor/revolt/event-loop/src/EventLoop/Internal/AbstractDriver.php(430): Revolt\EventLoop\Internal\DriverSuspension::{closure:Revolt\EventLoop\Internal\DriverSuspension::resume():61}()
> #10 /var/www/vendor/revolt/event-loop/src/EventLoop/Internal/AbstractDriver.php(621): Revolt\EventLoop\Internal\AbstractDriver->invokeMicrotasks()
> #11 [internal function]: Revolt\EventLoop\Internal\AbstractDriver->{closure:Revolt\EventLoop\Internal\AbstractDriver::createCallbackFiber():565}()
> #12 /var/www/vendor/revolt/event-loop/src/EventLoop/Internal/AbstractDriver.php(502): Fiber->resume()
> #13 /var/www/vendor/revolt/event-loop/src/EventLoop/Internal/AbstractDriver.php(558): Revolt\EventLoop\Internal\AbstractDriver->invokeCallbacks()
> #14 [internal function]: Revolt\EventLoop\Internal\AbstractDriver->{closure:Revolt\EventLoop\Internal\AbstractDriver::createLoopFiber():538}()
> #15 /var/www/vendor/revolt/event-loop/src/EventLoop/Internal/AbstractDriver.php(96): Fiber->resume()
> #16 /var/www/vendor/revolt/event-loop/src/EventLoop/Internal/DriverSuspension.php(117): Revolt\EventLoop\Internal\AbstractDriver->{closure:Revolt\EventLoop\Internal\AbstractDriver::__construct():90}()
> #17 /var/www/vendor/amphp/amp/src/Future.php(251): Revolt\EventLoop\Internal\DriverSuspension->suspend()
> #18 /var/www/vendor/amphp/parallel/src/Worker/ContextWorkerPool.php(274): Amp\Future->await()
> #19 /var/www/vendor/amphp/parallel/src/Worker/ContextWorkerPool.php(216): Amp\Parallel\Worker\ContextWorkerPool->pull()
> #20 /var/www/vendor/vimeo/psalm/src/Psalm/Internal/Fork/Pool.php(137): Amp\Parallel\Worker\ContextWorkerPool->getWorker()
> #21 /var/www/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Scanner.php(316): Psalm\Internal\Fork\Pool->runAll(Object(Psalm\Internal\Fork\InitScannerTask))
> #22 /var/www/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Scanner.php(266): Psalm\Internal\Codebase\Scanner->scanFilePaths(4)
> #23 /var/www/vendor/vimeo/psalm/src/Psalm/Codebase.php(444): Psalm\Internal\Codebase\Scanner->scanFiles(Object(Psalm\Internal\Codebase\ClassLikes), 4)
> #24 /var/www/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(429): Psalm\Codebase->scanFiles(4)
> #25 /var/www/vendor/vimeo/psalm/src/Psalm/Internal/Cli/Psalm.php(400): Psalm\Internal\Analyzer\ProjectAnalyzer->check('/var/www', false)
> #26 /var/www/vendor/vimeo/psalm/psalm(9): Psalm\Internal\Cli\Psalm::run(Array)
> #27 /var/www/vendor/bin/psalm(119): include('/var/www/vendor...')
> #28 {main}
> 
> Next Amp\Sync\ChannelException: Sending on the channel failed. Did the context die? in /var/www/vendor/amphp/byte-stream/src/StreamChannel.php:71
> Stack trace:
> #0 /var/www/vendor/amphp/parallel/src/Context/Internal/ContextChannel.php(29): Amp\ByteStream\StreamChannel->send('\x00\x00\x18\xAD\x17O:44:"Amp\\...')
> #1 /var/www/vendor/amphp/parallel/src/Worker/Internal/task-runner.php(77): Amp\Parallel\Context\Internal\ContextChannel->send(Object(Amp\Parallel\Worker\Internal\TaskSuccess))
> #2 /var/www/vendor/revolt/event-loop/src/EventLoop/Internal/AbstractDriver.php(430): Psalm\Internal\Fork\ForkContext::{closure:{closure:/var/www/vendor/amphp/parallel/src/Worker/Internal/task-runner.php:14}:47}()
> #3 /var/www/vendor/revolt/event-loop/src/EventLoop/Internal/AbstractDriver.php(621): Revolt\EventLoop\Internal\AbstractDriver->invokeMicrotasks()
> #4 [internal function]: Revolt\EventLoop\Internal\AbstractDriver->{closure:Revolt\EventLoop\Internal\AbstractDriver::createCallbackFiber():565}()
> #5 /var/www/vendor/revolt/event-loop/src/EventLoop/Internal/DriverSuspension.php(64): Fiber->resume(Object(Closure))
> #6 /var/www/vendor/revolt/event-loop/src/EventLoop/Internal/AbstractDriver.php(430): Revolt\EventLoop\Internal\DriverSuspension::{closure:Revolt\EventLoop\Internal\DriverSuspension::resume():61}()
> #7 /var/www/vendor/revolt/event-loop/src/EventLoop/Internal/AbstractDriver.php(621): Revolt\EventLoop\Internal\AbstractDriver->invokeMicrotasks()
> #8 [internal function]: Revolt\EventLoop\Internal\AbstractDriver->{closure:Revolt\EventLoop\Internal\AbstractDriver::createCallbackFiber():565}()
> #9 /var/www/vendor/revolt/event-loop/src/EventLoop/Internal/AbstractDriver.php(502): Fiber->resume()
> #10 /var/www/vendor/revolt/event-loop/src/EventLoop/Internal/AbstractDriver.php(558): Revolt\EventLoop\Internal\AbstractDriver->invokeCallbacks()
> #11 [internal function]: Revolt\EventLoop\Internal\AbstractDriver->{closure:Revolt\EventLoop\Internal\AbstractDriver::createLoopFiber():538}()
> #12 /var/www/vendor/revolt/event-loop/src/EventLoop/Internal/AbstractDriver.php(96): Fiber->resume()
> #13 /var/www/vendor/revolt/event-loop/src/EventLoop/Internal/DriverSuspension.php(117): Revolt\EventLoop\Internal\AbstractDriver->{closure:Revolt\EventLoop\Internal\AbstractDriver::__construct():90}()
> #14 /var/www/vendor/amphp/amp/src/Future.php(251): Revolt\EventLoop\Internal\DriverSuspension->suspend()
> #15 /var/www/vendor/amphp/parallel/src/Worker/ContextWorkerPool.php(274): Amp\Future->await()
> #16 /var/www/vendor/amphp/parallel/src/Worker/ContextWorkerPool.php(216): Amp\Parallel\Worker\ContextWorkerPool->pull()
> #17 /var/www/vendor/vimeo/psalm/src/Psalm/Internal/Fork/Pool.php(137): Amp\Parallel\Worker\ContextWorkerPool->getWorker()
> #18 /var/www/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Scanner.php(316): Psalm\Internal\Fork\Pool->runAll(Object(Psalm\Internal\Fork\InitScannerTask))
> #19 /var/www/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Scanner.php(266): Psalm\Internal\Codebase\Scanner->scanFilePaths(4)
> #20 /var/www/vendor/vimeo/psalm/src/Psalm/Codebase.php(444): Psalm\Internal\Codebase\Scanner->scanFiles(Object(Psalm\Internal\Codebase\ClassLikes), 4)
> #21 /var/www/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(429): Psalm\Codebase->scanFiles(4)
> #22 /var/www/vendor/vimeo/psalm/src/Psalm/Internal/Cli/Psalm.php(400): Psalm\Internal\Analyzer\ProjectAnalyzer->check('/var/www', false)
> #23 /var/www/vendor/vimeo/psalm/psalm(9): Psalm\Internal\Cli\Psalm::run(Array)
> #24 /var/www/vendor/bin/psalm(119): include('/var/www/vendor...')
> #25 {main}
> 
> Next Revolt\EventLoop\UncaughtThrowable: Uncaught Amp\Sync\ChannelException thrown in event loop callback Psalm\Internal\Fork\ForkContext::{closure:{closure:/var/www/vendor/amphp/parallel/src/Worker/Internal/task-runner.php:14}:47} defined in /var/www/vendor/amphp/parallel/src/Worker/Internal/task-runner.php:47; use Revolt\EventLoop::setErrorHandler() to gracefully handle such exceptions: Sending on the channel failed. Did the context die? in /var/www/vendor/revolt/event-loop/src/EventLoop/UncaughtThrowable.php:13
> Stack trace:
> #0 /var/www/vendor/revolt/event-loop/src/EventLoop/Internal/AbstractDriver.php(405): Revolt\EventLoop\UncaughtThrowable::throwingCallback(Object(Closure), Object(Amp\Sync\ChannelException))
> #1 /var/www/vendor/revolt/event-loop/src/EventLoop/Internal/DriverSuspension.php(127): Revolt\EventLoop\Internal\AbstractDriver::{closure:Revolt\EventLoop\Internal\AbstractDriver::error():403}()
> #2 /var/www/vendor/amphp/amp/src/Future.php(251): Revolt\EventLoop\Internal\DriverSuspension->suspend()
> #3 /var/www/vendor/amphp/parallel/src/Worker/ContextWorkerPool.php(274): Amp\Future->await()
> #4 /var/www/vendor/amphp/parallel/src/Worker/ContextWorkerPool.php(216): Amp\Parallel\Worker\ContextWorkerPool->pull()
> #5 /var/www/vendor/vimeo/psalm/src/Psalm/Internal/Fork/Pool.php(137): Amp\Parallel\Worker\ContextWorkerPool->getWorker()
> #6 /var/www/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Scanner.php(316): Psalm\Internal\Fork\Pool->runAll(Object(Psalm\Internal\Fork\InitScannerTask))
> #7 /var/www/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Scanner.php(266): Psalm\Internal\Codebase\Scanner->scanFilePaths(4)
> #8 /var/www/vendor/vimeo/psalm/src/Psalm/Codebase.php(444): Psalm\Internal\Codebase\Scanner->scanFiles(Object(Psalm\Internal\Codebase\ClassLikes), 4)
> #9 /var/www/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(429): Psalm\Codebase->scanFiles(4)
> #10 /var/www/vendor/vimeo/psalm/src/Psalm/Internal/Cli/Psalm.php(400): Psalm\Internal\Analyzer\ProjectAnalyzer->check('/var/www', false)
> #11 /var/www/vendor/vimeo/psalm/psalm(9): Psalm\Internal\Cli\Psalm::run(Array)
> #12 /var/www/vendor/bin/psalm(119): include('/var/www/vendor...')
> #13 {main}
> (Psalm 6.13.1@1e3b7f0a8ab32b23197b91107adc0a7ed8a05b51 crashed due to an uncaught Throwable)
> Uncaught Error: The event loop is already running in /var/www/vendor/revolt/event-loop/src/EventLoop/Internal/AbstractDriver.php:109
> Stack trace:
> #0 /var/www/vendor/revolt/event-loop/src/EventLoop.php(406): Revolt\EventLoop\Internal\AbstractDriver->run()
> #1 /var/www/vendor/vimeo/psalm/src/Psalm/Internal/Fork/ForkContext.php(175): Revolt\EventLoop::run()
> #2 /var/www/vendor/vimeo/psalm/src/Psalm/Internal/Fork/Pool.php(69): Psalm\Internal\Fork\ForkContext::start(Array, Object(Amp\Parallel\Ipc\LocalIpcHub), Object(Amp\Internal\WrappedCancellation), 5)
> #3 /var/www/vendor/amphp/parallel/src/Worker/ContextWorkerFactory.php(43): Amp\Parallel\Context\ContextFactory@anonymous->start(Array, Object(Amp\Internal\WrappedCancellation))
> #4 /var/www/vendor/amphp/parallel/src/Worker/ContextWorkerPool.php(248): Amp\Parallel\Worker\ContextWorkerFactory->create(Object(Amp\Internal\WrappedCancellation))
> #5 /var/www/vendor/amphp/amp/src/functions.php(33): Amp\Parallel\Worker\ContextWorkerPool::{closure:Amp\Parallel\Worker\ContextWorkerPool::pull():246}()
> #6 /var/www/vendor/revolt/event-loop/src/EventLoop/Internal/AbstractDriver.php(430): {closure:Amp\async():23}(NULL, NULL, Array)
> #7 /var/www/vendor/revolt/event-loop/src/EventLoop/Internal/AbstractDriver.php(567): Revolt\EventLoop\Internal\AbstractDriver->invokeMicrotasks()
> #8 [internal function]: Revolt\EventLoop\Internal\AbstractDriver->{closure:Revolt\EventLoop\Internal\AbstractDriver::createCallbackFiber():565}()
> #9 /var/www/vendor/revolt/event-loop/src/EventLoop/Internal/DriverSuspension.php(64): Fiber->resume(NULL)
> #10 /var/www/vendor/revolt/event-loop/src/EventLoop/Internal/AbstractDriver.php(430): Revolt\EventLoop\Internal\DriverSuspension::{closure:Revolt\EventLoop\Internal\DriverSuspension::resume():61}()
> #11 /var/www/vendor/revolt/event-loop/src/EventLoop/Internal/AbstractDriver.php(621): Revolt\EventLoop\Internal\AbstractDriver->invokeMicrotasks()
> #12 [internal function]: Revolt\EventLoop\Internal\AbstractDriver->{closure:Revolt\EventLoop\Internal\AbstractDriver::createCallbackFiber():565}()
> #13 /var/www/vendor/revolt/event-loop/src/EventLoop/Internal/AbstractDriver.php(502): Fiber->resume()
> #14 /var/www/vendor/revolt/event-loop/src/EventLoop/Internal/AbstractDriver.php(558): Revolt\EventLoop\Internal\AbstractDriver->invokeCallbacks()
> #15 [internal function]: Revolt\EventLoop\Internal\AbstractDriver->{closure:Revolt\EventLoop\Internal\AbstractDriver::createLoopFiber():538}()
> #16 /var/www/vendor/revolt/event-loop/src/EventLoop/Internal/AbstractDriver.php(96): Fiber->start()
> #17 /var/www/vendor/revolt/event-loop/src/EventLoop/Internal/DriverSuspension.php(117): Revolt\EventLoop\Internal\AbstractDriver->{closure:Revolt\EventLoop\Internal\AbstractDriver::__construct():90}()
> #18 /var/www/vendor/amphp/amp/src/Future.php(251): Revolt\EventLoop\Internal\DriverSuspension->suspend()
> #19 /var/www/vendor/amphp/parallel/src/Worker/ContextWorkerPool.php(274): Amp\Future->await()
> #20 /var/www/vendor/amphp/parallel/src/Worker/ContextWorkerPool.php(216): Amp\Parallel\Worker\ContextWorkerPool->pull()
> #21 /var/www/vendor/vimeo/psalm/src/Psalm/Internal/Fork/Pool.php(137): Amp\Parallel\Worker\ContextWorkerPool->getWorker()
> #22 /var/www/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Scanner.php(316): Psalm\Internal\Fork\Pool->runAll(Object(Psalm\Internal\Fork\InitScannerTask))
> #23 /var/www/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Scanner.php(266): Psalm\Internal\Codebase\Scanner->scanFilePaths(4)
> #24 /var/www/vendor/vimeo/psalm/src/Psalm/Codebase.php(444): Psalm\Internal\Codebase\Scanner->scanFiles(Object(Psalm\Internal\Codebase\ClassLikes), 4)
> #25 /var/www/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(429): Psalm\Codebase->scanFiles(4)
> #26 /var/www/vendor/vimeo/psalm/src/Psalm/Internal/Cli/Psalm.php(400): Psalm\Internal\Analyzer\ProjectAnalyzer->check('/var/www', false)
> #27 /var/www/vendor/vimeo/psalm/psalm(9): Psalm\Internal\Cli\Psalm::run(Array)
> #28 /var/www/vendor/bin/psalm(119): include('/var/www/vendor...')
> #29 {main}
> (Psalm 6.13.1@1e3b7f0a8ab32b23197b91107adc0a7ed8a05b51 crashed due to an uncaught Throwable)
> Uncaught Error: The event loop is already running in /var/www/vendor/revolt/event-loop/src/EventLoop/Internal/AbstractDriver.php:109
> Stack trace:
> #0 /var/www/vendor/revolt/event-loop/src/EventLoop.php(406): Revolt\EventLoop\Internal\AbstractDriver->run()
> #1 /var/www/vendor/vimeo/psalm/src/Psalm/Internal/Fork/ForkContext.php(175): Revolt\EventLoop::run()
> #2 /var/www/vendor/vimeo/psalm/src/Psalm/Internal/Fork/Pool.php(69): Psalm\Internal\Fork\ForkContext::start(Array, Object(Amp\Parallel\Ipc\LocalIpcHub), Object(Amp\Internal\WrappedCancellation), 5)
> #3 /var/www/vendor/amphp/parallel/src/Worker/ContextWorkerFactory.php(43): Amp\Parallel\Context\ContextFactory@anonymous->start(Array, Object(Amp\Internal\WrappedCancellation))
> #4 /var/www/vendor/amphp/parallel/src/Worker/ContextWorkerPool.php(248): Amp\Parallel\Worker\ContextWorkerFactory->create(Object(Amp\Internal\WrappedCancellation))
> #5 /var/www/vendor/amphp/amp/src/functions.php(33): Amp\Parallel\Worker\ContextWorkerPool::{closure:Amp\Parallel\Worker\ContextWorkerPool::pull():246}()
> #6 /var/www/vendor/revolt/event-loop/src/EventLoop/Internal/AbstractDriver.php(430): {closure:Amp\async():23}(NULL, NULL, Array)
> #7 /var/www/vendor/revolt/event-loop/src/EventLoop/Internal/AbstractDriver.php(621): Revolt\EventLoop\Internal\AbstractDriver->invokeMicrotasks()
> #8 [internal function]: Revolt\EventLoop\Internal\AbstractDriver->{closure:Revolt\EventLoop\Internal\AbstractDriver::createCallbackFiber():565}()
> #9 /var/www/vendor/revolt/event-loop/src/EventLoop/Internal/DriverSuspension.php(64): Fiber->resume(NULL)
> #10 /var/www/vendor/revolt/event-loop/src/EventLoop/Internal/AbstractDriver.php(430): Revolt\EventLoop\Internal\DriverSuspension::{closure:Revolt\EventLoop\Internal\DriverSuspension::resume():61}()
> #11 /var/www/vendor/revolt/event-loop/src/EventLoop/Internal/AbstractDriver.php(621): Revolt\EventLoop\Internal\AbstractDriver->invokeMicrotasks()
> #12 [internal function]: Revolt\EventLoop\Internal\AbstractDriver->{closure:Revolt\EventLoop\Internal\AbstractDriver::createCallbackFiber():565}()
> #13 /var/www/vendor/revolt/event-loop/src/EventLoop/Internal/AbstractDriver.php(502): Fiber->resume()
> #14 /var/www/vendor/revolt/event-loop/src/EventLoop/Internal/AbstractDriver.php(558): Revolt\EventLoop\Internal\AbstractDriver->invokeCallbacks()
> #15 [internal function]: Revolt\EventLoop\Internal\AbstractDriver->{closure:Revolt\EventLoop\Internal\AbstractDriver::createLoopFiber():538}()
> #16 /var/www/vendor/revolt/event-loop/src/EventLoop/Internal/AbstractDriver.php(96): Fiber->resume()
> #17 /var/www/vendor/revolt/event-loop/src/EventLoop/Internal/DriverSuspension.php(117): Revolt\EventLoop\Internal\AbstractDriver->{closure:Revolt\EventLoop\Internal\AbstractDriver::__construct():90}()
> #18 /var/www/vendor/amphp/amp/src/Future.php(251): Revolt\EventLoop\Internal\DriverSuspension->suspend()
> #19 /var/www/vendor/amphp/parallel/src/Worker/ContextWorkerPool.php(274): Amp\Future->await()
> #20 /var/www/vendor/amphp/parallel/src/Worker/ContextWorkerPool.php(216): Amp\Parallel\Worker\ContextWorkerPool->pull()
> #21 /var/www/vendor/vimeo/psalm/src/Psalm/Internal/Fork/Pool.php(137): Amp\Parallel\Worker\ContextWorkerPool->getWorker()
> #22 /var/www/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Scanner.php(316): Psalm\Internal\Fork\Pool->runAll(Object(Psalm\Internal\Fork\InitScannerTask))
> #23 /var/www/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Scanner.php(266): Psalm\Internal\Codebase\Scanner->scanFilePaths(4)
> #24 /var/www/vendor/vimeo/psalm/src/Psalm/Codebase.php(444): Psalm\Internal\Codebase\Scanner->scanFiles(Object(Psalm\Internal\Codebase\ClassLikes), 4)
> #25 /var/www/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(429): Psalm\Codebase->scanFiles(4)
> #26 /var/www/vendor/vimeo/psalm/src/Psalm/Internal/Cli/Psalm.php(400): Psalm\Internal\Analyzer\ProjectAnalyzer->check('/var/www', false)
> #27 /var/www/vendor/vimeo/psalm/psalm(9): Psalm\Internal\Cli\Psalm::run(Array)
> #28 /var/www/vendor/bin/psalm(119): include('/var/www/vendor...')
> #29 {main}
> (Psalm 6.13.1@1e3b7f0a8ab32b23197b91107adc0a7ed8a05b51 crashed due to an uncaught Throwable)
> Uncaught Amp\ByteStream\ClosedException: The stream was closed in /var/www/vendor/amphp/byte-stream/src/WritableResourceStream.php:98
> Stack trace:
> #0 /var/www/vendor/amphp/byte-stream/src/WritableResourceStream.php(248): Amp\ByteStream\WritableResourceStream::{closure:{closure:Amp\ByteStream\WritableResourceStream::__construct():77}:98}()
> #1 /var/www/vendor/amphp/socket/src/ResourceSocket.php(129): Amp\ByteStream\WritableResourceStream->write('0:{s:23:"\x00Psalm...')
> #2 /var/www/vendor/amphp/byte-stream/src/StreamChannel.php(69): Amp\Socket\ResourceSocket->write('\x00N\xD1\xD1\x19O:44:"Amp\\...')
> #3 /var/www/vendor/amphp/parallel/src/Context/Internal/ContextChannel.php(29): Amp\ByteStream\StreamChannel->send('\x00N\xD1\xD1\x19O:44:"Amp\\...')
> #4 /var/www/vendor/amphp/parallel/src/Worker/Internal/task-runner.php(77): Amp\Parallel\Context\Internal\ContextChannel->send(Object(Amp\Parallel\Worker\Internal\TaskSuccess))
> #5 /var/www/vendor/revolt/event-loop/src/EventLoop/Internal/AbstractDriver.php(430): Psalm\Internal\Fork\ForkContext::{closure:{closure:/var/www/vendor/amphp/parallel/src/Worker/Internal/task-runner.php:14}:47}()
> #6 /var/www/vendor/revolt/event-loop/src/EventLoop/Internal/AbstractDriver.php(621): Revolt\EventLoop\Internal\AbstractDriver->invokeMicrotasks()
> #7 [internal function]: Revolt\EventLoop\Internal\AbstractDriver->{closure:Revolt\EventLoop\Internal\AbstractDriver::createCallbackFiber():565}()
> #8 /var/www/vendor/revolt/event-loop/src/EventLoop/Internal/DriverSuspension.php(64): Fiber->resume(Object(Closure))
> #9 /var/www/vendor/revolt/event-loop/src/EventLoop/Internal/AbstractDriver.php(430): Revolt\EventLoop\Internal\DriverSuspension::{closure:Revolt\EventLoop\Internal\DriverSuspension::resume():61}()
> #10 /var/www/vendor/revolt/event-loop/src/EventLoop/Internal/AbstractDriver.php(621): Revolt\EventLoop\Internal\AbstractDriver->invokeMicrotasks()
> #11 [internal function]: Revolt\EventLoop\Internal\AbstractDriver->{closure:Revolt\EventLoop\Internal\AbstractDriver::createCallbackFiber():565}()
> #12 /var/www/vendor/revolt/event-loop/src/EventLoop/Internal/AbstractDriver.php(502): Fiber->resume()
> #13 /var/www/vendor/revolt/event-loop/src/EventLoop/Internal/AbstractDriver.php(558): Revolt\EventLoop\Internal\AbstractDriver->invokeCallbacks()
> #14 [internal function]: Revolt\EventLoop\Internal\AbstractDriver->{closure:Revolt\EventLoop\Internal\AbstractDriver::createLoopFiber():538}()
> #15 /var/www/vendor/revolt/event-loop/src/EventLoop/Internal/AbstractDriver.php(96): Fiber->resume()
> #16 /var/www/vendor/revolt/event-loop/src/EventLoop/Internal/DriverSuspension.php(117): Revolt\EventLoop\Internal\AbstractDriver->{closure:Revolt\EventLoop\Internal\AbstractDriver::__construct():90}()
> #17 /var/www/vendor/amphp/amp/src/Future.php(251): Revolt\EventLoop\Internal\DriverSuspension->suspend()
> #18 /var/www/vendor/amphp/parallel/src/Worker/ContextWorkerPool.php(274): Amp\Future->await()
> #19 /var/www/vendor/amphp/parallel/src/Worker/ContextWorkerPool.php(216): Amp\Parallel\Worker\ContextWorkerPool->pull()
> #20 /var/www/vendor/vimeo/psalm/src/Psalm/Internal/Fork/Pool.php(137): Amp\Parallel\Worker\ContextWorkerPool->getWorker()
> #21 /var/www/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Scanner.php(316): Psalm\Internal\Fork\Pool->runAll(Object(Psalm\Internal\Fork\InitScannerTask))
> #22 /var/www/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Scanner.php(266): Psalm\Internal\Codebase\Scanner->scanFilePaths(4)
> #23 /var/www/vendor/vimeo/psalm/src/Psalm/Codebase.php(444): Psalm\Internal\Codebase\Scanner->scanFiles(Object(Psalm\Internal\Codebase\ClassLikes), 4)
> #24 /var/www/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(429): Psalm\Codebase->scanFiles(4)
> #25 /var/www/vendor/vimeo/psalm/src/Psalm/Internal/Cli/Psalm.php(400): Psalm\Internal\Analyzer\ProjectAnalyzer->check('/var/www', false)
> #26 /var/www/vendor/vimeo/psalm/psalm(9): Psalm\Internal\Cli\Psalm::run(Array)
> #27 /var/www/vendor/bin/psalm(119): include('/var/www/vendor...')
> #28 {main}
> 
> Next Amp\Sync\ChannelException: Sending on the channel failed. Did the context die? in /var/www/vendor/amphp/byte-stream/src/StreamChannel.php:71
> Stack trace:
> #0 /var/www/vendor/amphp/parallel/src/Context/Internal/ContextChannel.php(29): Amp\ByteStream\StreamChannel->send('\x00N\xD1\xD1\x19O:44:"Amp\\...')
> #1 /var/www/vendor/amphp/parallel/src/Worker/Internal/task-runner.php(77): Amp\Parallel\Context\Internal\ContextChannel->send(Object(Amp\Parallel\Worker\Internal\TaskSuccess))
> #2 /var/www/vendor/revolt/event-loop/src/EventLoop/Internal/AbstractDriver.php(430): Psalm\Internal\Fork\ForkContext::{closure:{closure:/var/www/vendor/amphp/parallel/src/Worker/Internal/task-runner.php:14}:47}()
> #3 /var/www/vendor/revolt/event-loop/src/EventLoop/Internal/AbstractDriver.php(621): Revolt\EventLoop\Internal\AbstractDriver->invokeMicrotasks()
> #4 [internal function]: Revolt\EventLoop\Internal\AbstractDriver->{closure:Revolt\EventLoop\Internal\AbstractDriver::createCallbackFiber():565}()
> #5 /var/www/vendor/revolt/event-loop/src/EventLoop/Internal/DriverSuspension.php(64): Fiber->resume(Object(Closure))
> #6 /var/www/vendor/revolt/event-loop/src/EventLoop/Internal/AbstractDriver.php(430): Revolt\EventLoop\Internal\DriverSuspension::{closure:Revolt\EventLoop\Internal\DriverSuspension::resume():61}()
> #7 /var/www/vendor/revolt/event-loop/src/EventLoop/Internal/AbstractDriver.php(621): Revolt\EventLoop\Internal\AbstractDriver->invokeMicrotasks()
> #8 [internal function]: Revolt\EventLoop\Internal\AbstractDriver->{closure:Revolt\EventLoop\Internal\AbstractDriver::createCallbackFiber():565}()
> #9 /var/www/vendor/revolt/event-loop/src/EventLoop/Internal/AbstractDriver.php(502): Fiber->resume()
> #10 /var/www/vendor/revolt/event-loop/src/EventLoop/Internal/AbstractDriver.php(558): Revolt\EventLoop\Internal\AbstractDriver->invokeCallbacks()
> #11 [internal function]: Revolt\EventLoop\Internal\AbstractDriver->{closure:Revolt\EventLoop\Internal\AbstractDriver::createLoopFiber():538}()
> #12 /var/www/vendor/revolt/event-loop/src/EventLoop/Internal/AbstractDriver.php(96): Fiber->resume()
> #13 /var/www/vendor/revolt/event-loop/src/EventLoop/Internal/DriverSuspension.php(117): Revolt\EventLoop\Internal\AbstractDriver->{closure:Revolt\EventLoop\Internal\AbstractDriver::__construct():90}()
> #14 /var/www/vendor/amphp/amp/src/Future.php(251): Revolt\EventLoop\Internal\DriverSuspension->suspend()
> #15 /var/www/vendor/amphp/parallel/src/Worker/ContextWorkerPool.php(274): Amp\Future->await()
> #16 /var/www/vendor/amphp/parallel/src/Worker/ContextWorkerPool.php(216): Amp\Parallel\Worker\ContextWorkerPool->pull()
> #17 /var/www/vendor/vimeo/psalm/src/Psalm/Internal/Fork/Pool.php(137): Amp\Parallel\Worker\ContextWorkerPool->getWorker()
> #18 /var/www/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Scanner.php(316): Psalm\Internal\Fork\Pool->runAll(Object(Psalm\Internal\Fork\InitScannerTask))
> #19 /var/www/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Scanner.php(266): Psalm\Internal\Codebase\Scanner->scanFilePaths(4)
> #20 /var/www/vendor/vimeo/psalm/src/Psalm/Codebase.php(444): Psalm\Internal\Codebase\Scanner->scanFiles(Object(Psalm\Internal\Codebase\ClassLikes), 4)
> #21 /var/www/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(429): Psalm\Codebase->scanFiles(4)
> #22 /var/www/vendor/vimeo/psalm/src/Psalm/Internal/Cli/Psalm.php(400): Psalm\Internal\Analyzer\ProjectAnalyzer->check('/var/www', false)
> #23 /var/www/vendor/vimeo/psalm/psalm(9): Psalm\Internal\Cli\Psalm::run(Array)
> #24 /var/www/vendor/bin/psalm(119): include('/var/www/vendor...')
> #25 {main}
> 
> Next Revolt\EventLoop\UncaughtThrowable: Uncaught Amp\Sync\ChannelException thrown in event loop callback Psalm\Internal\Fork\ForkContext::{closure:{closure:/var/www/vendor/amphp/parallel/src/Worker/Internal/task-runner.php:14}:47} defined in /var/www/vendor/amphp/parallel/src/Worker/Internal/task-runner.php:47; use Revolt\EventLoop::setErrorHandler() to gracefully handle such exceptions: Sending on the channel failed. Did the context die? in /var/www/vendor/revolt/event-loop/src/EventLoop/UncaughtThrowable.php:13
> Stack trace:
> #0 /var/www/vendor/revolt/event-loop/src/EventLoop/Internal/AbstractDriver.php(405): Revolt\EventLoop\UncaughtThrowable::throwingCallback(Object(Closure), Object(Amp\Sync\ChannelException))
> #1 /var/www/vendor/revolt/event-loop/src/EventLoop/Internal/DriverSuspension.php(127): Revolt\EventLoop\Internal\AbstractDriver::{closure:Revolt\EventLoop\Internal\AbstractDriver::error():403}()
> #2 /var/www/vendor/amphp/amp/src/Future.php(251): Revolt\EventLoop\Internal\DriverSuspension->suspend()
> #3 /var/www/vendor/amphp/parallel/src/Worker/ContextWorkerPool.php(274): Amp\Future->await()
> #4 /var/www/vendor/amphp/parallel/src/Worker/ContextWorkerPool.php(216): Amp\Parallel\Worker\ContextWorkerPool->pull()
> #5 /var/www/vendor/vimeo/psalm/src/Psalm/Internal/Fork/Pool.php(137): Amp\Parallel\Worker\ContextWorkerPool->getWorker()
> #6 /var/www/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Scanner.php(316): Psalm\Internal\Fork\Pool->runAll(Object(Psalm\Internal\Fork\InitScannerTask))
> #7 /var/www/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Scanner.php(266): Psalm\Internal\Codebase\Scanner->scanFilePaths(4)
> #8 /var/www/vendor/vimeo/psalm/src/Psalm/Codebase.php(444): Psalm\Internal\Codebase\Scanner->scanFiles(Object(Psalm\Internal\Codebase\ClassLikes), 4)
> #9 /var/www/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(429): Psalm\Codebase->scanFiles(4)
> #10 /var/www/vendor/vimeo/psalm/src/Psalm/Internal/Cli/Psalm.php(400): Psalm\Internal\Analyzer\ProjectAnalyzer->check('/var/www', false)
> #11 /var/www/vendor/vimeo/psalm/psalm(9): Psalm\Internal\Cli\Psalm::run(Array)
> #12 /var/www/vendor/bin/psalm(119): include('/var/www/vendor...')
> #13 {main}
> (Psalm 6.13.1@1e3b7f0a8ab32b23197b91107adc0a7ed8a05b51 crashed due to an uncaught Throwable)

**Comment by danog** [comment]
This is not a bug, it's just an OOM, which is now visible: further increasing swap space should fix the issue.

**Comment by s1lver** [comment]
> This is not a bug, it's just an OOM, which is now visible: further increasing swap space should fix the issue.

I increased SWAP to 4GB and that did not solve the problem.

"The bug" in this case is that Psalm cannot handle a large number of files.

**Comment by danog** [comment]
Is the swap completely filled up during execution? If yes, further increase
 it

**Comment by s1lver** [comment]
> Is the swap completely filled up during execution? If yes, further increase it

Yes, of course.

As I mentioned earlier this issue appeared starting from version **6.1.0**. Before version **6.1.0** PSALM handled that number of files perfectly.
