### ISSUE TITLE
LSP: Support for native classes/methods/functions

### ISSUE THREAD

**Issue by iluuu1994** [vimeo/psalm#1863]
Psalm currently does not support completing or viewing information of native classes, methods and functions. This would be incredibly beneficial. [PHPStorm stubs](https://github.com/JetBrains/phpstorm-stubs) are open source and could be useful.

Psalm currently has a list of classes and methods in `CallMap` which does not contain any documentation and also wouldn't allow for "Jump to definition" as PHPStorm does.

**Comment by muglug** [comment]
Yeah, I noticed this the other day. It can only currently complete classes it's already seen - I think it would be sufficient for the completion list to just be drawn from `get_declared_classes()` at startup

**Comment by iluuu1994** [comment]
<img width="364" alt="image" src="https://user-images.githubusercontent.com/1752683/61454304-d1017900-a960-11e9-917d-11cecf4d9fd7.png">

When I hover over a native function it just says "[object Object]" in VSCode. Also, autocompletion doesn't work with functions yet. 🙂

**Comment by muglug** [comment]
Native functions should work now, having just pushed 8d63d5d. But there's a better solution (the argument map should be pre populated with both the function symbol _and_ its arguments (in string form) so no further calculation is necessary. Right now user functions (like `B\foo` in the test you added) won't get suggestions.

**Comment by muglug** [comment]
I should have time to fix that over the weekend, but feel free to work on it if you have time beforehand.

**Comment by iluuu1994** [comment]
@muglug Maybe the screenshot was confusing. It's not the signature helper that displays this but the hover. The problem persists on master.

**Comment by muglug** [comment]
would you mind stopping the languages server, clearing cache (`--clear-global-cache`), resuming and see if the problem reoccurs? And if it does, can you reproduce it in a test?

**Comment by iluuu1994** [comment]
@muglug Problem persists after `--clear-global-cache`. I'll see if I can reproduce it in a test tomorrow 🙂
