### ISSUE TITLE
session_set_cookie_params can take options

### ISSUE THREAD

**Issue by iluuu1994** [vimeo/psalm#2051]
```php
session_set_cookie_params([
  'samesite' => 'Strict',
]);

@session_start();
```

> ERROR: InvalidArgument - 3:27 - Argument 1 of session_set_cookie_params expects int, array{samesite: string(Strict)} provided
> 
> ERROR: UnusedFunctionCall - 3:1 - The call to session_set_cookie_params is not used

https://psalm.dev/r/27cae239cd

Two issues:

* `session_set_cookie_params` [accepts an array of options](https://www.php.net/manual/en/function.session-set-cookie-params.php). This is [already configured this way](https://github.com/vimeo/psalm/blob/d424cb3ccd2f99ecb96eded4d70e2bd8cc222fad/src/Psalm/Internal/CallMap_73_delta.php#L45). Not sure why it isn't working.
* ~The "is not used" is also wrong.~ Solved by #2053

**Comment by LeSuisse** [comment]
It looks like the issue has been resolved, should this be closed?

**Comment by swiffer** [comment]
it's not solved for the `samesite` array option atm, is it?

https://github.com/vimeo/psalm/pull/7215/files
