### ISSUE TITLE
possible issue with shaped array not being interchangeable with non-empty-array

### ISSUE THREAD

**Issue by SignpostMarv** [vimeo/psalm#2613]
If a type is restricted to `non-empty-array`, a shaped array should be allowed: https://psalm.dev/r/c8fe243f5f

Appending to the `list` child of a shaped array with a value-restricted param appears to alter the parent type from the initial shaped array to a `non-empty-array`: https://psalm.dev/r/f24c852ae9

**Comment by SignpostMarv** [comment]
@muglug https://psalm.dev/r/f24c852ae9 is still bugged

**Comment by muglug** [comment]
That's a different bug, more succinctly here: https://psalm.dev/r/31d5cccec3

**Comment by muglug** [comment]
that different bug was fixed int c77f2cd

**Comment by SignpostMarv** [comment]
*waits for psalm.dev to update*

**Comment by SignpostMarv** [comment]
@muglug https://psalm.dev/r/31d5cccec3 still appears to be bugged in c77f2cd ?
