### ISSUE TITLE
LSP: PHP errors break protocol stream

### ISSUE THREAD

**Issue by matthijskooijman** [vimeo/psalm#4142]
It seems that when running the LSP (maybe also otherwise), any PHP errors are printed on stdout *and* stderr. Since stdout is the JSONRPC protocol stream, this breaks the protocol.

I originally noticed this due to `PHP Notice:  Undefined offset: 1 in /home/matthijs/.config/composer/vendor/felixfbecker/advanced-json-rpc/lib/Dispatcher.php on line 141`, but that's not the subject of this issue.

To reproduce, you can use the following patch to induce a PHP error:

```diff
--- a/src/Psalm/Internal/LanguageServer/LanguageServer.php
+++ b/src/Psalm/Internal/LanguageServer/LanguageServer.php
@@ -89,6 +89,8 @@ class LanguageServer extends AdvancedJsonRpc\Dispatcher
         $this->project_analyzer = $project_analyzer;
 
         $this->protocolWriter = $writer;
+        $foo = [];
+        $foo[0];
 
         $this->protocolReader = $reader;
         $this->protocolReader->on(
```

Then run the LSP:

```
psalm --language-server
PHP Notice:  Undefined offset: 0 in /home/matthijs/.config/composer/vendor/vimeo/psalm/src/Psalm/Internal/LanguageServer/LanguageServer.php on line 93

Notice: Undefined offset: 0 in /home/matthijs/.config/composer/vendor/vimeo/psalm/src/Psalm/Internal/LanguageServer/LanguageServer.php on line 93
```
The `PHP Notice` line is on stderr, the `Notice` line on stdout.

I looked around the code shortly to see where this happens, but I could not quickly find it.

**Comment by matthijskooijman** [comment]
Note that it also prints a `\n` before *and* after the line, the newline before is what tripped up my client in the first place, hiding the error that comes after it, so it took me a while to figure this one out.

**Comment by muglug** [comment]
I guess I could set the `error_level` to `E_ERROR` when running the language server, to prevent this

**Comment by matthijskooijman** [comment]
> I guess I could set the error_level to E_ERROR when running the language server, to prevent this

I'm not sure that helps, because:
 - In case of E_ERROR messages, the protocol would still break
 - I think the problem is not the default error printing, that happens on stderr. E.g. if I create a dummy php file that produces a notice, I get the notice only once, on stderr. So there is something in the way Psalm configures error handling that causes the additional printing on stdout, so it should be possible to *not* configure it like that?

**Comment by orklah** [comment]
I think this has been fixed by https://github.com/vimeo/psalm/pull/4143

**Comment by matthijskooijman** [comment]
It has been a while that I reported this, but I think #4143 does not really fix this issue. It might fix one particular error, but AFAICS it does nothing to change handling of errors, so I think this issue still exists (or at least is not fixed by that particular PR).

**Comment by orklah** [comment]
Ok, please reopen an issue if you can reproduce it, but we currently don't have maintainers that use LSP or know much about it, so your best chance of seeing this fixed is by proposing a PR...

**Comment by matthijskooijman** [comment]
I'm not really using Psalm anymore right now. If I come back PHP dev later, I might check if this still happens, leaving this closed for now is fine by me.
