### ISSUE TITLE
MixedInferredReturnType when non-existing class is used in the return condition

### ISSUE THREAD

**Issue by vudaltsov** [vimeo/psalm#4395]
While the `UndefinedClass` error is ok, the `MixedInferredReturnType` is unexpected, because the code is absolutely valid.

https://psalm.dev/r/83a79939ec

**Comment by orklah** [comment]
This seems fixed now

**Comment by weirdan** [comment]
@vudaltsov it works if you suppress UndefinedClass: https://psalm.dev/r/d1f944a9f8

**Comment by vudaltsov** [comment]
The issue is not fixed.

`ReflectionUnionType` was just an example, any non-existent class can be used.

https://psalm.dev/r/7312a91c0a
https://3v4l.org/9moCq

**Comment by orklah** [comment]
Just for curiosity, what's the use case behind that? What's the reason behind not fixing a level 8 issue while still being bothered by a level 1 issue?

**Comment by vudaltsov** [comment]
@orklah , forward compatibility with PHP 8, for example (the original example of the issue).
