### ISSUE TITLE
Commit 82f35c1 and XDebug causing odd MethodSignatureMismatch error

### ISSUE THREAD

**Issue by scheb** [vimeo/psalm#4459]
I'm seeing an odd `MethodSignatureMismatch` error being reported by Psalm since commit 82f35c1454fbead0f8d74a75c08c2632ff6fee45 (released with Psalm 4.1.0). With the previous commit 438bcc6ab7e42291beec9e0d274e2ee49eff76ac the issue doesn't appear (see log below).

I'm unable to reproduce the issue on psalm.dev. I've figured out the error only appears when the XDebug extension is loaded, which is probably the reason why I cannot reproduce it on psalm.dev (I guess you don't have XDebug loaded there). So I'm trying my best to explain what the situation in the code is.

I'm a bit baffled what to do with the error, whether it is intended or not. The relation to the XDebug extension alone is odd enough.

### Error Description

My environment:
```
PHP 7.4.11 (cli) (built: Oct 18 2020 19:39:42) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.11, Copyright (c), by Zend Technologies
    with Xdebug v2.9.8, Copyright (c) 2002-2020, by Derick Rethans
```

Psalm version 4.1.0 (or any commit from 82f35c1454fbead0f8d74a75c08c2632ff6fee45 on)

The Psalm error appearing is:
```
ERROR: MethodSignatureMismatch - src/bundle/Security/Authentication/Token/TwoFactorTokenFactory.php:11:91 - Argument 3 of Scheb\TwoFactorBundle\Security\Authentication\Token\TwoFactorTokenFactory::create has wrong type 'array<array-key, mixed>', expecting 'array<array-key, string>' as defined by Scheb\TwoFactorBundle\Security\Authentication\Token\TwoFactorTokenFactoryInterface::create (see https://psalm.dev/042)
    public function create(TokenInterface $authenticatedToken, string $providerKey, array $twoFactorProviders): TwoFactorTokenInterface
```

TwoFactorTokenFactoryInterface.php:
```
interface TwoFactorTokenFactoryInterface
{
    /**
     * Create a new TwoFactorToken.
     *
     * @param string      $providerKey        The firewall name
     * @param string[]    $twoFactorProviders The two-factor provider aliases, which are currently available
     */
    public function create(TokenInterface $authenticatedToken, string $providerKey, array $twoFactorProviders): TwoFactorTokenInterface;
}
```

TwoFactorTokenFactoryInterface.php:
```
class TwoFactorTokenFactory implements TwoFactorTokenFactoryInterface
{
    public function create(TokenInterface $authenticatedToken, string $providerKey, array $twoFactorProviders): TwoFactorTokenInterface
    {
        return new TwoFactorToken($authenticatedToken, null, $providerKey, $twoFactorProviders);
    }
}
```

As you can see the `TwoFactorTokenFactory` class implementing the interface doesn't have any types declared in PHPDoc. Psalm is complaining that the method signatures don't match, since the interface declares a string-array and the implementation declares nothing, therefore assuming a mixed-array. One could argue this is a valid error, but:

- adding the exact same PHPDoc annotation from the interface in `TwoFactorTokenFactory` doesn't make the error go away
- not loading the XDebug extension makes the error go away

### Logs

Logs testing 438bcc6ab7e42291beec9e0d274e2ee49eff76ac against 82f35c1454fbead0f8d74a75c08c2632ff6fee45. I've also done another test run with `--no-cache` to make sure it's not a caching issue.

```
composer require vimeo/psalm:dev-master#438bcc6ab7e42291beec9e0d274e2ee49eff76ac
./composer.json has been updated
Running composer update vimeo/psalm
Loading composer repositories with package information
Updating dependencies
Lock file operations: 0 installs, 1 update, 0 removals
  - Upgrading vimeo/psalm (dev-master 82f35c1 => dev-master 438bcc6)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 0 installs, 1 update, 0 removals
  - Syncing vimeo/psalm (dev-master 438bcc6) into cache
  - Upgrading vimeo/psalm (dev-master 82f35c1 => dev-master 438bcc6): Checking out 438bcc6ab7 from cache
Generating autoload files
78 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
composer/package-versions-deprecated: Generating version class...
composer/package-versions-deprecated: ...done generating version class

vendor/bin/psalm
Scanning files...
Analyzing files...

░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░  60 / 107 (56%)
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░

------------------------------
No errors found!
------------------------------
300 other issues found.
You can display them with --show-info=true
------------------------------

Checks took 8.53 seconds and used 273.879MB of memory
Psalm was able to infer types for 91.4565% of the codebase

composer require vimeo/psalm:dev-master#82f35c1454fbead0f8d74a75c08c2632ff6fee45
./composer.json has been updated
Running composer update vimeo/psalm
Loading composer repositories with package information
Updating dependencies
Lock file operations: 0 installs, 1 update, 0 removals
  - Upgrading vimeo/psalm (dev-master 438bcc6 => dev-master 82f35c1)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 0 installs, 1 update, 0 removals
  - Syncing vimeo/psalm (dev-master 82f35c1) into cache
  - Upgrading vimeo/psalm (dev-master 438bcc6 => dev-master 82f35c1): Checking out 82f35c1454 from cache
Generating autoload files
composer/package-versions-deprecated: Generating version class...
composer/package-versions-deprecated: ...done generating version class
78 packages you are using are looking for funding.
Use the `composer fund` command to find out more!

vendor/bin/psalm
Scanning files...
Analyzing files...

░░░░░░░░░░░░░░░░░░░░░░░░░E░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░  60 / 107 (56%)
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░

ERROR: MethodSignatureMismatch - src/bundle/Security/Authentication/Token/TwoFactorTokenFactory.php:11:91 - Argument 3 of Scheb\TwoFactorBundle\Security\Authentication\Token\TwoFactorTokenFactory::create has wrong type 'array<array-key, mixed>', expecting 'array<array-key, string>' as defined by Scheb\TwoFactorBundle\Security\Authentication\Token\TwoFactorTokenFactoryInterface::create (see https://psalm.dev/042)
    public function create(TokenInterface $authenticatedToken, string $providerKey, array $twoFactorProviders): TwoFactorTokenInterface


------------------------------
1 errors found
------------------------------
300 other issues found.
You can display them with --show-info=true
------------------------------

Checks took 9.00 seconds and used 273.989MB of memory
Psalm was able to infer types for 91.4565% of the codebase
```

If you need any additional information, please reach out. I'm happy to help figuring out what's going on there.

**Comment by weirdan** [comment]
> not loading the XDebug extension makes the error go away

That sounds pretty weird. Psalm uses `composer/xdebug-handler` to disable Xdebug, so even if you have it enabled in your `php.ini` it should still be automatically disabled when Psalm runs.

**Comment by muglug** [comment]
If you get latest master I've just pushed a change that _might_ affect you? The only change that commit _did_ make was to change the order of when Psalm loads stubs for xdebug.

**Comment by scheb** [comment]
@muglug Yes, that fixes it, thank you!

Can confirm the error is still there with 67554dd017, and with cbd09adb2a19 it's gone.

**Comment by muglug** [comment]
Great!

**Comment by scheb** [comment]
Thanks for the super quick response!

**Comment by scheb** [comment]
It may be necessary to remove the cache, otherwise the error might persist:
```
rm -rf ~/.cache/psalm
rm -rf /tmp/psalm
```
