### ISSUE TITLE
Report `@var` used on methods and `@param` used on properties

### ISSUE THREAD

**Issue by weirdan** [vimeo/psalm#4813]
People tend to confuse `@var` and `@param`. When they do they think Psalm ignores the type they specified and come file issues. One recent example is #4811, but it's not the first time it happens.

I think it would be useful to report tags that are used in the context where they are ignored.

**Comment by weirdan** [comment]
https://psalm.dev/r/f7907841eb

**Comment by muglug** [comment]
Seems fixed now!

**Comment by AndrolGenhald** [comment]
`@param` still isn't reported on properties, but #7369 is a more general issue that should cover this.
