### ISSUE TITLE
Invalid MissingDependency error

### ISSUE THREAD

**Issue by ADmad** [vimeo/psalm#5007]
Running psalm 4.4.0 on PHP 7.2 shows error `SimpleXMLElement depends on class or interface stringable that does not exist` for any reference to `SimpleXMLElement`.

**Comment by lukasbestle** [comment]
Same issue for us, only on GitHub Actions though and with PHP 7.4.13: https://github.com/getkirby/kirby/runs/1701172723?check_suite_focus=true

**Comment by lukasbestle** [comment]
I'm pretty sure this is because of the `$codebase->php_major_version >= 8` check. If the analyzed code doesn't actually use any PHP 8 features yet, Psalm does not load the stub, which then breaks the `CoreGenericClasses.phpstub` that relies on the `Stringable` interface.

I'm wondering why the PHP 8 stubs are not always loaded for PHP versions < 8.0. Would that break something else or was it done for performance reasons?

**Comment by weirdan** [comment]
> I'm wondering why the PHP 8 stubs are not always loaded for PHP versions < 8.0. 

To correctly check your code Psalm needs *accurate* stubs. E.g. it would not flag calls to `ReflectionClass::getAttributes()` in the codebase targeting PHP 7.3 if it had loaded stubs for 8.0

**Comment by lukasbestle** [comment]
OK, that makes sense.

How does Psalm know which PHP version(s) the codebase targets? And what if the code should be able to run on multiple different PHP versions like PHP 7.3-8.0?

In any case, the bug is basically that the version-independent stub for `SimpleXMLElement` uses `Stringable`. So maybe the fix is to have two different stubs for `SimpleXMLElement`: One for PHP 8 with `Stringable` and one for PHP < 8 without.

**Comment by weirdan** [comment]
> How does Psalm know which PHP version(s) the codebase targets?

In the order of preference:

1. CLI argument (`--php-version`)
2. Config file ([`phpVersion` attribute](https://psalm.dev/docs/running_psalm/configuration/#phpversion))
3. First of `5.4.0`, `5.5.0`, `5.6.0`, `7.0.0`, `7.1.0`, `7.2.0`, `7.3.0`, `7.4.0`, `8.0.0` that satisfies your `composer.json` constraints (`require.php` key), if you have any.

>  And what if the code should be able to run on multiple different PHP versions like PHP 7.3-8.0?

Run Psalm multiple times, with `--php-version=7.3`, `--php-version=7.4`, etc.

**Comment by orklah** [comment]
> How does Psalm know which PHP version(s) the codebase targets? And what if the code should be able to run on multiple different PHP versions like PHP 7.3-8.0?

https://psalm.dev/docs/running_psalm/configuration/#phpversion

> In any case, the bug is basically that the version-independent stub for `SimpleXMLElement` uses `Stringable`. So maybe the fix is to have two different stubs for `SimpleXMLElement`: One for PHP 8 with `Stringable` and one for PHP < 8 without. Or maybe we can get rid of the use of `Stringable` completely.

Maybe a stub for Stringable with just a __toString method could make it work for every version?

**Comment by 2e3s** [comment]
> Maybe a stub for Stringable with just a __toString method could make it work for every version?

No. Such a stub would incorrectly add `Stringable` to the namespace of a codebase which may not have in fact. Hence, leading to incorrect analysis results.

I think Psalm needs to support different stubs for different versions, and the stubs would be grandfathered if the new PHP version has not changed the contract.

**Comment by orklah** [comment]
I'd not call this a big deal.

Psalm already adds every stubbed class in every old version of PHP if I'm not mistaken. The only impact I can see is if a codebase not yet in PHP8 use Stringable without Polyfill. In this case, Psalm would not return an error.

It seems like an acceptable compromise given the additional burden of creating and maintaining versionned stubs. I guess if you're up for it, it'd would be nice to have, but otherwise, I'm not sure it's a reasonable fix for this issue.

**Comment by lukasbestle** [comment]
@weirdan @orklah Thank you very much for the insights on the `phpVersion` option and flag. 👍

Regarding this issue: Do we really need to have `implements \Stringable` in [this line](https://github.com/vimeo/psalm/commit/b30842e9811718c02c1442b4ce465068273b836e#diff-34d358b776541824d633dce138ec8282f95adc5b7e12dabb31503e71edd8e9b1R2218)? As PHP 8.0 automatically adds the `Stringable` interface to every class implementing `__toString()`, wouldn't it be an alternative to include the method definition of `__toString()` in the `SimpleXMLElement` stub? This would make the stub compatible with all PHP versions.

**Comment by orklah** [comment]
> Regarding this issue: Do we really need to have `implements \Stringable` in [this line](https://github.com/vimeo/psalm/commit/b30842e9811718c02c1442b4ce465068273b836e#diff-34d358b776541824d633dce138ec8282f95adc5b7e12dabb31503e71edd8e9b1R2218)? As PHP 8.0 automatically adds the `Stringable` interface to every class implementing `__toString()`, wouldn't it be an alternative to include the method definition of `__toString()` in the `SimpleXMLElement` stub? This would make the stub compatible with all PHP versions.

This could be a solution but Psalm should not report this as an error:
https://3v4l.org/8WKd9
Which I think it will if we remove Stringable from the stubs

**Comment by lukasbestle** [comment]
Could this be solved by implementing the "magic `Stringable` interface behavior" from PHP 8 in Psalm as well? Meaning: Like PHP, Psalm should automatically add the `Stringable` interface to every class that implements `__toString()` if the `phpVersion` option is set to `8.0` or higher.

**Comment by orklah** [comment]
Not sure. It may already be the case. You could try to push a PR to test that 😃

**Comment by lukasbestle** [comment]
To be honest I don't have a good overview over the Psalm codebase, so I wouldn't know where to start. If someone wants to continue with the idea, go ahead. :)

**Comment by orklah** [comment]
> To be honest I don't have a good overview over the Psalm codebase, so I wouldn't know where to start. If someone wants to continue with the idea, go ahead. :)

No need to know the internals, There's a file ToStringTest in tests/ directory, you could add my example in it. You then try to remove \Stringable in the stubs. If it pass, the issue is resolved. If it doesn't pass, we'll need to refine the solution or try another one 😄

**Comment by lukasbestle** [comment]
@orklah Ah, right! I misunderstood your message. It turns out there is [already a test case for exactly this behavior](https://github.com/vimeo/psalm/blob/4.4.1/tests/ToStringTest.php#L172-L186), so we are fine.

I have fixed this issue in https://github.com/vimeo/psalm/pull/5037.

**Comment by orklah** [comment]
Oh, cool!

**Comment by ADmad** [comment]
I am still seeing the same error using the phar of `4.5.1` release.
