### ISSUE TITLE
Constexpr evaluator underflow / overflow handling for + and -

### ISSUE THREAD

**Issue by BafS** [vimeo/psalm#5921]
I have a type error bug (similar to https://github.com/vimeo/psalm/issues/5505) when using binary shifts

Psalm version: v4.7.3

**Error**
```
Uncaught TypeError: Argument 2 passed to Psalm\Type::getInt() must be of the type int or null, float given, called in phar:///.../vendor/psalm/phar/psalm.phar/src/Psalm/Internal/Analyzer/Statements/Expression/BinaryOp/NonDivArithmeticOpAnalyzer.php on line 162 and defined in phar:///.../vendor/psalm/phar/psalm.phar/src/Psalm/Type.php:129
```

**psalm.xml**
```xml
<?xml version="1.0"?>
<psalm
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns="https://getpsalm.org/schema/config"
    xsi:schemaLocation="https://getpsalm.org/schema/config vendor/vimeo/psalm/config.xsd"
    xmlns:xi="http://www.w3.org/2001/XInclude"
>
    <projectFiles>
        <file name="bug-psalm.php" />
    </projectFiles>
</psalm>
```

**bug-psalm.php**
```php
<?php

const MASK = (1 << 63) - (1 << 20);
```

**Comment by BafS** [comment]
Yes, https://psalm.dev/r/b5c187cf0c

**Comment by weirdan** [comment]
The code handling `Plus`, `Minus`, and `ShiftLeft` should be fixed to handle float results, the way it's already done for `Pow` and `Mul`:

https://github.com/vimeo/psalm/blob/cf6a4e70c5edfae4357211d52502b3ad856a0c13/src/Psalm/Internal/Analyzer/Statements/Expression/BinaryOp/NonDivArithmeticOpAnalyzer.php#L311-L340

**Comment by BafS** [comment]
Pow is not completely fixed btw, you need to check PHP_INT_MAX but PHP_INT_MIN too.

See https://psalm.dev/r/e4949e1737
