### ISSUE TITLE
Invalid links on getpslam.org

### ISSUE THREAD

**Issue by ADmad** [vimeo/psalm#599]
https://getpsalm.org/ has links to non-existent wiki pages of this repo.

**Comment by muglug** [comment]
Thanks - fixed now

**Comment by ADmad** [comment]
You missed the link on "config" for "Add a config:" :slightly_smiling_face:

**Comment by muglug** [comment]
Ah thanks, fixed too

**Comment by ADmad** [comment]
Welcome.
