### ISSUE TITLE
PHP 8.2 has `PHP Error: Creation of dynamic property PhpParser\Node\Stmt\Class_::$namespacedName is deprecated`

### ISSUE THREAD

**Issue by TysonAndre** [vimeo/psalm#7007]
https://wiki.php.net/rfc/deprecate_dynamic_properties deprecates it in 8.2

This should be using setAttribute('namespacedNameObject') and getAttribute(string $key, $default = null) instead - I'm not familiar with whether the properties are considered to be part of the public API yet.

- Checking for errno=E_DEPRECATED and  `Creation of dynamic property PhpParser\Node` at the start of $errstr is another option

https://github.com/vimeo/psalm/pull/5091 was added in september to set dynamic properties.

**Comment by orklah** [comment]
Oh, I fixed a lot of them here: https://github.com/vimeo/psalm/pull/6656 but seems like I missed some

**Comment by winstrand** [comment]
Still present in v3.4.3
Deprecated: Creation of dynamic property PhpParser\Node\Stmt\PropertyProperty::$fqsen
Deprecated: Creation of dynamic property PhpParser\Node\Stmt\ClassMethod::$fqsen
Deprecated: Creation of dynamic property PhpParser\Node\Stmt\Namespace_::$fqsen
Deprecated: Creation of dynamic property PhpParser\Node\Stmt\Class_::$fqsen
