### ISSUE TITLE
Disallow `static::` for compile-time resolution

### ISSUE THREAD

**Issue by AndrolGenhald** [vimeo/psalm#7712]
https://psalm.dev/r/580d2d9849 https://3v4l.org/L1hFi
https://psalm.dev/r/ac2623c9d5 https://3v4l.org/BvTJU

Not sure if there are any other places this can happen.

**Comment by orklah** [comment]
weird, the second link doesn't show an error anymore

**Comment by AndrolGenhald** [comment]
That probably happened when I fixed it so that you can use `self::FOOBAR` instead of having to do `MyClass::FOOBAR`.

**Comment by orklah** [comment]
Only static::class is still not flagged. The rest seems solved https://psalm.dev/r/1570ea8550
