### ISSUE TITLE
UndefinedConstant when using enum property as const array key

### ISSUE THREAD

**Issue by Brajk19** [vimeo/psalm#9373]
When using `Enum::CASE->value` or `Enum::CASE->name` as key in constant, psalm throws UndefinedConstant error.
No error is thrown when enum property is used as key in regular array (not const).

https://psalm.dev/r/3307971eb7

**Comment by weirdan** [comment]
The linked commit looks like it should fix it.

**Comment by ygottschalk** [comment]
Still working on it, did not really fix the issue. PR should be incoming today
